name: agro_observatory
version: "1.0.0"
profile: agro_observatory

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

flags:
  send_anonymous_usage_stats: false

models:
  agro_observatory:
    staging:
      +materialized: view
      +schema: staging
